petstagram/accounts/urls.py
from django.urls import path, include
from .views import RegisterUserView, LoginUserView, LogoutUserView, \
    ProfileDetailsView, ProfileEditView, ProfileDeleteView

urlpatterns = [

    # localhost:8000/accounts/register/
    path('register/', RegisterUserView.as_view(), name='register'),

    # localhost:8000/accounts/login/
    path('login/', LoginUserView.as_view(), name='login'),

    path('logout/', LogoutUserView.as_view(), name='logout'),

    path('profile/<int:pk>/', include([

        # localhost:8000/accounts/profile/<int:pk>/
        path('', ProfileDetailsView.as_view(), name='profile-details'),

        # localhost:8000/accounts/profile/<int:pk>/edit/
        path('edit/', ProfileEditView.as_view(), name='profile-edit'),

        # localhost:8000/accounts/profile/<int:pk>/delete/
        path('delete/', ProfileDeleteView.as_view(), name='profile-delete'),
    ]
    )),

]

petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # localhost:8000/admin/
    path('admin/', admin.site.urls),

    # localhost:8000
    path('', include('petstagram.common.urls')),

    # localhost:8000/accounts/
    path('accounts/', include('petstagram.accounts.urls')),

    # localhost:8000/pets/
    path('pets/', include('petstagram.pets.urls')),

    # localhost:8000/photos/
    path('photos/', include('petstagram.photos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/accounts/models.py
from enum import Enum
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinLengthValidator
from petstagram.accounts.validators import only_alpha_validator


class ChoicesMixin:
    @classmethod
    def choices(cls):
        return [(choice.value, choice.value) for choice in cls]


class ChoicesStringMixin(ChoicesMixin):
    @classmethod
    def max_length(cls):
        return max(len(x.value) for x in cls)


class Gender(ChoicesStringMixin, Enum):
    MALE = "Male"
    FEMALE = "Female"
    DO_NOT_SHOW = "Do not show"


class PetstagramUser(AbstractUser):
    NAME_MIN_LENGTH = 2
    NAME_MAX_LENGTH = 30
    first_name = models.CharField(
        max_length=NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(NAME_MIN_LENGTH),
            only_alpha_validator,
        )
    )
    last_name = models.CharField(
        max_length=NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(NAME_MIN_LENGTH),
            only_alpha_validator,
        )
    )
    email = models.EmailField(unique=True)
    profile_picture = models.URLField(blank=True, null=True)
    gender = models.CharField(
        max_length=Gender.max_length(),
        choices=Gender.choices(),
        default="Do not show"
    )

    @property
    def full_name(self):
        if self.first_name or self.last_name:
            return f'{self.first_name} {self.last_name}'
        return None

petstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models
from petstagram.photos.models import Photo

UserModel = get_user_model()


class Comment(models.Model):
    comment_text = models.TextField(max_length=300)
    date_and_time_of_publication = models.DateField(auto_now=True)
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-date_and_time_of_publication"]


class Like(models.Model):
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

petstagram/pets/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify

UserModel = get_user_model()


class Pet(models.Model):
    name = models.CharField(
        max_length=30,
        null=False,
        blank=False,
    )
    personal_photo = models.URLField(
        blank=False,
        null=False,
    )
    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )
    slug = models.SlugField(unique=True, editable=False)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    # in order to have your own representation of the object instead of "Pet object (1)"
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.id}')
        return super().save(*args, **kwargs)

petstagram/photos/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models
from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_size

UserModel = get_user_model()


# Create your models here.
class Photo(models.Model):
    photo = models.ImageField(upload_to='images', validators=(validate_file_size,))
    description = models.TextField(
        max_length=300,
        validators=[MinLengthValidator(10)],  # this validator is accessible after import
        blank=True,
        null=True,
    )
    location = models.TextField(
        max_length=30,
        blank=True,
        null=True,
    )
    tagged_pets = models.ManyToManyField(
        Pet, blank=True
    )
    date_of_publication = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

petstagram/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django import forms

UserModel = get_user_model()


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Username'}))
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", 'placeholder': 'Password'}))

petstagram/accounts/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.views import LoginView, LogoutView
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from petstagram.accounts.forms import RegisterUserForm, LoginUserForm

UserModel = get_user_model()


class RegisterUserView(CreateView):
    template_name = 'register-page.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        result = super().form_valid(form)

        login(self.request, self.object)

        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['next'] = self.request.GET.get("next", '')

        return context

    def get_success_url(self):
        return self.request.POST.get("next", self.success_url)


class LoginUserView(LoginView):
    template_name = 'login-page.html'
    form_class = LoginUserForm


class LogoutUserView(LogoutView):
    next_page = reverse_lazy("login")


class ProfileDetailsView(DetailView):
    template_name = 'profile-details-page.html'
    model = UserModel

    profile_image = static('images/person.png')

    def get_profile_picture(self):
        if self.object.profile_picture is not None:
            return self.object.profile_picture
        return self.profile_image

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['profile_image'] = self.get_profile_picture()
        context['pets'] = self.request.user.pet_set.all()

        return context


class ProfileEditView(UpdateView):
    template_name = 'profile-edit-page.html'


class ProfileDeleteView(DeleteView):
    template_name = 'profile-delete-page.html'

petstagram/accounts/templates/login-page.html
{% extends 'base.html' %}
{% load custom_filters %}
<!-- Starts Main Section -->

    {% block content %}
    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="{% url 'login' %}" method="post">
                {{ form }}
                <input type="hidden" value="{{ next }}" name="next">
                {% csrf_token %}
                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have account? <a href="{% url 'register' %}?next={{ next }}">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->
    {% endblock %}

petstagram/accounts/templates/profile-delete-page.html
{% extends 'base.html' %}
{% load static %}

<!-- Starts Main Section -->

    {% block content %}
    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="{% static '/images/are_you_sure_cat.gif' %}" alt="are you sure cat gif">
        </div>
    <!-- End Delete Profile Section -->
    {% endblock %}

petstagram/accounts/templates/profile-details-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Start Profile Details Section -->
    <div class="profile">

        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
            <div class="profile_img">
                <div class="image">

                    <!-- Profile Image -->
                    <img src="{{ profile_image }}" alt="img8">
                </div>
            </div>
            <div class="personal">
                <div class="edit">
                    <!-- User Username -->
                    <p>{{ object.username }}</p>

                    <!-- IF the viewer is the owner of the profile -->
                    <!-- Link to Edit Profile Page -->
                    <a href="{% url 'profile-edit' object.pk %}">
                        <img class="edit-img" src="{% static '/images/edit-pen-icon-6.jpg' %}" alt="edit button">
                    </a>

                    <!-- Link to Delete Profile Page -->
                    <a href="{% url 'profile-delete' object.pk %}">
                        <img class="bin-img" src="{% static '/images/icon-remove-22.jpg' %}" alt="bin button">
                    </a>
                    <!-- End IF the viewer is the owner of the profile -->

                </div>
                <div class="data">

                    <!-- Total Number of Photos by the User -->
                    <span>{{ object.photo_set.count }}</span>
                    <p>photos</p>

                    <!-- Total Number of Pets owned by the User -->
                    <span>{{ object.pet_set.count }}</span>
                    <p>pets</p>

                    <!-- Total Number of Likes for the User -->
                    <span>{{ object.like_set.count }}</span>
                    <p>likes</p>
                </div>
                <!-- User First and Last Name IF Added -->
                <h3 class="names">
                    {% if full_name %}
                        {{ object.full_name }}
                    {% endif %}
                </h3>

                <!-- User Email Address -->
                <p class="email">{{ object.email }}</p>

                <!-- User Gender IF Added -->
                <p class="gender">{{ object.gender }}</p>
            </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
            <div class="statuses">
                {% for pet in object.pet_set.all %}
                    <!-- Start 1st Pet Details Page -->
                    <!-- Link to First Pet Details Page -->
                    <a href="{% url 'pet-details' request.user.username pet.slug %}">
                        <div class="head-pet">
                            <div class="status">
                                <div class="image">
                                    <!-- Pet Image -->
                                    <img src="{{ pet.personal_photo }}" alt="pet img">
                                </div>
                            </div>
                            <!-- Pet Name -->
                            <p>{{ pet.name }}</p>
                        </div>
                    </a>
                    <!-- End 1st Pet Details Page -->
                {% endfor %}

            </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">
            {% for photo in object.photo_set.all %}
                <!-- Link to Last Uploaded Pet Photo -->
                <a href="{% url 'photo-details' photo.pk %}">
                    <!-- Pet Photo -->
                    <img src="{{ photo.photo.url }}"
                         alt="{{ photo.name }}">
                </a>
            {% endfor %}

        </div>
    </div>
    <!-- End Profile Details Section -->
{% endblock %}

petstagram/accounts/templates/profile-edit-page.html
{% extends 'base.html' %}
{% load static %}
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->

    {% block content %}
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
    <!-- End Edit Profile Section -->
    {% endblock %}

<!-- End Main Section -->

petstagram/accounts/templates/register-page.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
    <!-- Start Register Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>
            <!-- Start Register Form-->
            <form action="{% url 'register' %}" method="post">
                {% csrf_token %}
                {{ form.username.errors }}
                {{ form.username|placeholder:"Username" }}
                {{ form.email.errors }}
                {{ form.email|placeholder:"Email" }}
                {{ form.password1.errors }}
                {{ form.password2.errors }}
                {{ form.password1|placeholder:"Password" }}
                {{ form.password2|placeholder:"Repeat password" }}

                <input type="hidden" name="next" value="{{ next }}">
                <!-- Register Button-->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->
        </div>
        <div class="second-option"><p>Have an account?
            <!-- Link to Login Page-->
            <a href="{% url 'login' %}">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section-->
{% endblock %}